name: "Swift Doc Coverage"
description: "Documentation coverage command-line utility for Swift files."
author: "Iurii Khvorost"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      run: cd ${{ github.action_path }}

    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swift-doc-coverage-${{ hashFiles('Package.resolved') }}

    - shell: bash
      run: make install

    - shell: bash
      run: cd -
    
    - shell: bash
      run: swift-doc-coverage ${{ inputs.inputs }}
      
#    - run: npm i && node action.js
#      shell: bash


branding:
  icon: "book"
  color: "orange"
