name: "Swift Doc Coverage"
description: "Documentation coverage command-line utility for Swift files."
author: "Iurii Khvorost"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cp -r "${{ github.action_path }}" _action

    - uses: actions/cache@v3
      with:
        path: _action/.build
        key: ${{ runner.os }}-action-${{ hashFiles('**/_action/Package.resolved') }}

    # Install
    - shell: bash
      run: |
        cd _action
        make install
        cd -

    # Run
    - shell: bash
      run: |
        swift-doc-coverage ${{ inputs.inputs }}
#        npm i && node action.js


branding:
  icon: "book"
  color: "orange"
