name: "Swift Doc Coverage"
description: "Documentation coverage command-line utility for Swift files."
author: "Iurii Khvorost"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ${{ github.action_path }}/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

    - shell: bash
      run: |
        cd ${{ github.action_path }}
        make install
        cd -
    
    - shell: bash
      run: swift-doc-coverage ${{ inputs.inputs }}
      
#    - run: npm i && node action.js
#      shell: bash
#    - run: ${{ github.action_path }}/install.sh
#      shell: bash
#    - run: swift-doc-coverage "${{ inputs.inputs }}"
#      shell: bash

branding:
  icon: "book"
  color: "orange"
