name: "Swift Doc Coverage"
description: "Documentation coverage command-line utility for Swift files."
author: "Iurii Khvorost"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true
    default: ""

  token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir _action
        cp "${{ github.action_path }}/Package.resolved" _action/Package.resolved
        cp "${{ github.action_path }}/package-lock.json" _action/package-lock.json

    - uses: actions/cache@v3
      with:
        path: |
          ${{ github.action_path }}/.build
          ${{ github.action_path }}/node_modules
        key: ${{ runner.os }}-action-${{ hashFiles('**/_action/Package.resolved', '**/_action/package-lock.json') }}#

    - shell: bash
      run: |
        cd ${{ github.action_path }}
        make install
        npm install
        cd -

    # Run
    - shell: bash
      run: |
        swift-doc-coverage ${{ inputs.inputs }} -r json -o ./result.json
        TOKEN="${{ github.token }}" node ${{ github.action_path }}/action.js


branding:
  icon: "book"
  color: "orange"
