name: "Swift Doc Coverage"
description: "Documentation coverage command-line utility for Swift files."
author: "Iurii Khvorost"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true

  token:
    required: true
    description: 'Personal access token (PAT) used to fetch the repository.'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir _sdc
        cp -r ${{ github.action_path }} _sdc

    - uses: actions/cache@v3
      with:
        path: |
          _sdc/.build
          _sdc/node_modules
        key: ${{ runner.os }}-action-${{ hashFiles('**/_sdc/Package.resolved', '**/_sdc/package-lock.json') }}#

    - shell: bash
      run: |
        cd _sdc
        ls
        make install
        npm install
        cd -

    # Run
    - shell: bash
      run: |
        swift-doc-coverage ${{ inputs.inputs }} -r json -o "${{ github.workspace }}/result.json"
        TOKEN="${{ inputs.token }}" FILE="${{ github.workspace }}/result.json" REPOSITORY="${{ github.repository }}" node ${{ github.action_path }}/action.js


branding:
  icon: "book"
  color: "orange"
