name: "Swift Doc Coverage"
description: "Documentation coverage command-line utility for Swift files."
author: "Iurii Khvorost"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cp -r "${{ github.action_path }}/Package.resolved" "${{ github.workspace }}/swift-doc-coverage-hash"

    - uses: actions/cache@v3
      with:
        path: ${{ github.action_path }}/.build
        key: ${{ runner.os }}-swift-doc-coverage-${{ hashFiles('**/swift-doc-coverage-hash') }}

    - shell: bash
      run: | 
        cd ${{ github.action_path }}
        make install
        cd -

    - shell: bash
      run: |
        swift-doc-coverage ${{ inputs.inputs }}
#        npm i && node action.js


branding:
  icon: "book"
  color: "orange"
