name: "Swift Doc Coverage"
description: "Documentation coverage command-line utility for Swift files."
author: "Iurii Khvorost"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p _cache/.build
        cp "${{ github.action_path }}/Package.resolved" '_cache/cache.lock'

    - uses: actions/cache@v3
      with:
        path: _cache/.build
        key: ${{ runner.os }}-swift-doc-coverage-${{ hashFiles('**/_cache/cache.lock') }}

    - shell: bash
      run: | 
#        mv '_cache/.build' "${{ github.action_path }}/.build"
        cd ${{ github.action_path }}
        make install
        cd -
#        mv "${{ github.action_path }}/.build" '_cache/.build'

    # Run
    - shell: bash
      run: |
        swift-doc-coverage ${{ inputs.inputs }}
#        npm i && node action.js


branding:
  icon: "book"
  color: "orange"
