name: Build

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Code Coverage
      uses: ikhvorost/swift-doc-coverage@develop
      with:
        inputs: "Hello"

    - name: Save art
      run: echo "{message:'Hello'}" > test.json
      
    - uses: actions/upload-artifact@v3
      with:
        name: Test
        path: test.json

#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: |
#        swift test --enable-code-coverage -v
#        xcrun llvm-cov export -format="lcov" .build/debug/swift-doc-coveragePackageTests.xctest/contents/macos/swift-doc-coveragePackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex='_CSwiftSyntax|SwiftDocCoverageTests|ArgumentParser|SwiftSyntaxParser|SwiftSyntax|ArgumentParserToolInfo' > info.lcov
#        bash <(curl -s https://codecov.io/bash)
